// sorting time comparison for three different string types

/*
    [Valverde Computing copyright notice]

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    As an exception, the copyright holders of this Library grant you permission to
    (i) compile an Application with the Library, and
    (ii) distribute the Application containing code generated by the Library and
    added to the Application during this compilation process under terms of your choice,
    provided you also meet the terms and conditions of the Application license.

*/

#include <iostream>
#include <chrono>
#include <string.h>
#include <algorithm>
#include "Direct.h"
#include "Symbiont.h"
#include "Head.h"
#include "Sorts.h"

using namespace std;
using namespace std::chrono;

// Only calls distribution(generator) on the average, one time for every four characters.
// Should be faster than calling it on every character, I think
template<typename T, typename U, typename V, typename W>
void generateRandomStrings(T tArr[], U uArr[], V vArr[], W wArr, int sizeArray, int sizeString)
{
    char radixString[] = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    const int radixLen = sizeof(radixString) - 1; // it's null-terminated
    unsigned seed = std::chrono::system_clock::now().time_since_epoch().count();
    std::default_random_engine generator(seed);
    std::uniform_int_distribution<unsigned long long>
    distribution(numeric_limits<unsigned long long>::min(), numeric_limits<unsigned long long>::max());
    int uint64Length = sizeString/8 + 1; // rounding up to having more than enough random bits
    if (sizeString%8 == 0) --uint64Length; // rounding back the even cases to just enough bits
    union byteRand
    {
        uint64_t uint64Rand[128];
        uint8_t  uint8Rand[1024];
        char     charRand[1025];
    };
    byteRand overlay;

    // This loop should create four identical string arrays of different types
    for (int i = 0; i < sizeArray; ++i)
    {
        for (int j = 0; j < uint64Length; ++j)
        {
            overlay.uint64Rand[j] = distribution(generator);
        }
        for (int j = 0; j < sizeString; ++j)
        {
            overlay.uint8Rand[j] = radixString[overlay.uint8Rand[j] % radixLen];
        }
        overlay.charRand[sizeString] = 0;
        tArr[i].reserve(sizeString);
        tArr[i].assign(overlay.charRand);
        uArr[i].reserve(sizeString);
        uArr[i].assign(overlay.charRand);
        vArr[i].reserve(sizeString);
        vArr[i].assign(overlay.charRand);
        wArr[i].reserve(sizeString);
        wArr[i].assign(overlay.charRand);
    }
}

const int string10 = 10;
const int string100 = 100;
const int string1K = 1000;

const int array100 = 100;
const int array10K = 10000;
const int array1M = 1000000;

template<typename T>
void doQuick(T arr[], int size, string type)
{
    // Merge sort and print out measured statistics
    compares = 0;
    swaps = 0;
    duration<double, nano> sortTime = duration<double, nano> (0);
    high_resolution_clock::time_point start = high_resolution_clock::now();
    quickSortInvoke(arr, size);
    sortTime = duration_cast<duration<double>> (high_resolution_clock::now() - start);
    cout.precision(3);
    cout << fixed << type << ": " << chrono::duration <double, micro> (sortTime).count() << " microseconds, "
         << swaps << " swaps, " << compares << " compares" << endl;
}

template<typename T>
void doMerge(T arr[], int size, string type)
{
    // Merge sort and print out measured statistics
    compares = 0;
    swaps = 0;
    duration<double, nano> sortTime = duration<double, nano> (0);
    high_resolution_clock::time_point start = high_resolution_clock::now();
    mergeSortInvoke(arr, size);
    sortTime = duration_cast<duration<double>> (high_resolution_clock::now() - start);
    cout.precision(3);
    cout << fixed << type << ": " << chrono::duration <double, micro> (sortTime).count() << " microseconds, "
         << swaps << " swaps, " << compares << " compares" << endl << flush;
}

void doFour10ByteQuick(int size)
{
    // Create three different string type arrays with identical contents and quick sort them
    Direct<char, string10> dirArr[size];

    Symbiont<string10> symArr[size];
    symArr[0].dropAnchorKInit(symArr, size); // Extra work for Kaldane Symbiont

    typedef Head<string10> head;
    head headArr[size];
    head::tail tailArr[size];
    headArr[0].dropAnchorKInit(headArr, tailArr, size); // Extra work for Kaldane Head and Direct tail

    string strArr[size];

    generateRandomStrings(dirArr, symArr, headArr, strArr, size, string10);
    cout << endl << "Quick Sort " << size << " " << string10 << "-byte strings" << endl;
    doQuick(dirArr, size, "Direct");
    doQuick(symArr, size, "Symbiont");
    doQuick(headArr, size, "Head");
    doQuick(strArr, size, "std::string");
}

void doFour10ByteMerge(int size)
{
    // Create three different string type arrays with identical contents and quick sort them
    Direct<char, string10> dirArr[size];

    Symbiont<string10> symArr[size];
    symArr[0].dropAnchorKInit(symArr, size); // Extra work for Kaldane Symbiont

    typedef Head<string10> head;
    head headArr[size];
    head::tail tailArr[size];
    headArr[0].dropAnchorKInit(headArr, tailArr, size); // Extra work for Kaldane Head and Direct tail

    string strArr[size];

    generateRandomStrings(dirArr, symArr, headArr, strArr, size, string10);
    cout << endl << "Merge Sort " << size << " " << string10 << "-byte strings" << endl;
    doMerge(dirArr, size, "Direct");
    doMerge(symArr, size, "Symbiont");
    doMerge(headArr, size, "Head");
    doMerge(strArr, size, "std::string");
}

void doFour100ByteQuick(int size)
{
    // Create three different string type arrays with identical contents and quick sort them
    Direct<char, string100> dirArr[size];

    Symbiont<string100> symArr[size];
    symArr[0].dropAnchorKInit(symArr, size); // Extra work for Kaldane Symbiont

    typedef Head<string100> head;
    head headArr[size];
    head::tail tailArr[size];
    headArr[0].dropAnchorKInit(headArr, tailArr, size); // Extra work for Kaldane Head and Direct tail

    string strArr[size];

    generateRandomStrings(dirArr, symArr, headArr, strArr, size, string100);
    cout << endl << "Quick Sort " << size << " " << string100 << "-byte strings" << endl;
    doQuick(dirArr, size, "Direct");
    doQuick(symArr, size, "Symbiont");
    doQuick(headArr, size, "Head");
    doQuick(strArr, size, "std::string");
}

void doFour100ByteMerge(int size)
{
    // Create three different string type arrays with identical contents and quick sort them
    Direct<char, string100> dirArr[size];

    Symbiont<string100> symArr[size];
    symArr[0].dropAnchorKInit(symArr, size); // Extra work for Kaldane Symbiont

    typedef Head<string100> head;
    head headArr[size];
    head::tail tailArr[size];
    headArr[0].dropAnchorKInit(headArr, tailArr, size); // Extra work for Kaldane Head and Direct tail

    string strArr[size];

    generateRandomStrings(dirArr, symArr, headArr, strArr, size, string100);
    cout << endl << "Merge Sort " << size << " " << string100 << "-byte strings" << endl;
    doMerge(dirArr, size, "Direct");
    doMerge(symArr, size, "Symbiont");
    doMerge(headArr, size, "Head");
    doMerge(strArr, size, "std::string");
}

void doFour1KByteQuick(int size)
{
    // Create three different string type arrays with identical contents and quick sort them
    Direct<char, string1K> dirArr[size];

    Symbiont<string1K> symArr[size];
    symArr[0].dropAnchorKInit(symArr, size); // Extra work for Kaldane Symbiont

    typedef Head<string1K> head;
    head headArr[size];
    head::tail tailArr[size];
    headArr[0].dropAnchorKInit(headArr, tailArr, size); // Extra work for Kaldane Head and Direct tail

    string strArr[size];

    generateRandomStrings(dirArr, symArr, headArr, strArr, size, string1K);
    cout << endl << "Quick Sort " << size << " " << string1K << "-byte strings" << endl;
    doQuick(dirArr, size, "Direct");
    doQuick(symArr, size, "Symbiont");
    doQuick(headArr, size, "Head");
    doQuick(strArr, size, "std::string");
}

void doFour1KByteMerge(int size)
{
    // Create three different string type arrays with identical contents and quick sort them
    Direct<char, string1K> dirArr[size];

    Symbiont<string1K> symArr[size];
    symArr[0].dropAnchorKInit(symArr, size); // Extra work for Kaldane Symbiont

    typedef Head<string1K> head;
    head headArr[size];
    head::tail tailArr[size];
    headArr[0].dropAnchorKInit(headArr, tailArr, size); // Extra work for Kaldane Head and Direct tail

    string strArr[size];

    generateRandomStrings(dirArr, symArr, headArr, strArr, size, string1K);
    cout << endl << "Merge Sort " << size << " " << string1K << "-byte strings" << endl;
    doMerge(dirArr, size, "Direct");
    doMerge(symArr, size, "Symbiont");
    doMerge(headArr, size, "Head");
    doMerge(strArr, size, "std::string");
}

int main()
{
    cout << endl << endl << "Three different string types, identical in content and" << endl
         << "sorting logic, but not in timings." << endl << endl
         << "Note that the number of swaps and compares for identical arrays," << endl
         << "   using the identical code: these statistics should be identical." << endl << endl
         << "Remember to set the C++11 switch in the IDE or compiler!" << endl << endl
         << "Remember to use release builds if you are analyzing performance," << endl
         << "otherwise Symbionts will be very slow!" << endl << endl
         << "Remember to set the \"ulimit -s\" soft and hard stack limits to unlimited," <<endl
         << "otherwise it can die!]" << endl << endl;
    try // so you can see the exception names in release code execution
    {
        doFour10ByteQuick(array100);
        doFour10ByteMerge(array100);
        doFour100ByteQuick(array100);
        doFour100ByteMerge(array100);
        doFour1KByteQuick(array100);
        doFour1KByteMerge(array100);
        doFour10ByteQuick(array10K);
        doFour10ByteMerge(array10K);
        doFour100ByteQuick(array10K);
        doFour100ByteMerge(array10K);
        doFour1KByteQuick(array10K);
        doFour1KByteMerge(array10K);
        doFour10ByteQuick(array1M);
        cout << endl << endl << "warning: the std::string merge sorts of 1 million"
             << " records can take 6740 times longer!"
             << endl << "(30 minutes or so on my i5-3570 CPU)" << endl << endl;
        doFour10ByteMerge(array1M);
        doFour100ByteQuick(array1M);
        doFour100ByteMerge(array1M);
        doFour1KByteQuick(array1M);
        doFour1KByteMerge(array1M);
    }
    catch (...)
    {
        std::exception_ptr p = std::current_exception();
        cerr << "Exception: "
             << (p ?
                 p.__cxa_exception_type()->name() :
                 "Anonymous")
             << endl;
    }
    return 0;
}
